name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: stable
          cache: true

      - uses: imjasonh/setup-ko@v0.6

      - run: ko build --base-import-paths
